sudo: required
services:
  - docker

before_install:
  - docker build -t patbowe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true patbowe/docker-react npm run test -- --coverage 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-777957234239"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
